version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=CitizenEase
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5434:5432'

volumes:
  postgres: